version: '3'

services:
    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'express-boilerplate'
        volumes:
            - database:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/local/bin/healthcheck.sh',
                    '--su-mysql',
                    '--connect',
                    '--innodb_initialized',
                ]
        networks:
            - app
        ports:
            - 3309:3306

volumes:
    database:

networks:
    app:
