name: celosiajs_boilerplate-production

services:
    database:
        image: postgres:17.2-alpine
        volumes:
            - database:/var/lib/postgresql/data
        networks:
            - database
            - server
        environment:
            POSTGRES_DB: celosiajs_boilerplate
            POSTGRES_USER_FILE: /run/secrets/database-postgres-user
            POSTGRES_PASSWORD_FILE: /run/secrets/database-postgres-password
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d $$POSTGRES_DB']
            interval: 30s
            timeout: 20s
            start_period: 1s
            start_interval: 5s
            retries: 5
        restart: unless-stopped
        secrets:
            - database-postgres-user
            - database-postgres-password

    database-migration:
        build:
            context: .
            dockerfile: ./Dockerfile.migration
        networks:
            - database
        environment:
            DATABASE_URL_FILE: /run/secrets/database-url
        depends_on:
            database:
                condition: service_healthy
        secrets:
            - database-url

    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        stop_signal: SIGTERM
        stop_grace_period: 30s
        volumes:
            - server-logs:/app/Logs/
        networks:
            - server
        ports:
            - '8080:8080/tcp'
        environment:
            DATABASE_URL_FILE: /run/secrets/database-url
            HOST: 0.0.0.0
            PORT: 8080

            ACCESS_TOKEN_SECRET_FILE: /run/secrets/server-access-token-secret
            ACCESS_TOKEN_EXPIRE: 60 # 1 Minute

            REFRESH_TOKEN_SECRET_FILE: /run/secrets/server-refresh-token-secret
            REFRESH_TOKEN_EXPIRE: 2592000 # 30 Days

            RATE_LIMITER_MAX: 100
            RATE_LIMITER_WINDOW: 60

            PASSWORD_HASH_SECRET_FILE: /run/secrets/server-password-hash-secret

            CORS_ORIGIN: http://localhost:3000

            LOG_LEVEL: info
            LOG_PATH: /app/Logs/

        depends_on:
            database-migration:
                condition: service_completed_successfully
        restart: unless-stopped
        secrets:
            - database-url
            - server-access-token-secret
            - server-refresh-token-secret
            - server-password-hash-secret

volumes:
    database:
    server-logs:

networks:
    server:
    database:

secrets:
    database-url:
        file: ./secrets/database-url

    server-access-token-secret:
        file: ./secrets/server/access-token-secret
    server-refresh-token-secret:
        file: ./secrets/server/refresh-token-secret
    server-password-hash-secret:
        file: ./secrets/server/password-hash-secret

    database-postgres-user:
        file: ./secrets/database/postgres-user
    database-postgres-password:
        file: ./secrets/database/postgres-password
