name: celosiajs_boilerplate-production

services:
    database:
        image: postgres:17.2-alpine
        volumes:
            - database:/var/lib/postgresql/data
        networks:
            - database
            - server
        env_file:
            - .env.production.database.local
        healthcheck:
            test: ['CMD', 'pg_isready', '-d', '$$POSTGRES_DB']
            interval: 30s
            timeout: 20s
            start_period: 1s
            start_interval: 5s
            retries: 5
        restart: unless-stopped

    database-migration:
        build:
            context: .
            dockerfile: ./Dockerfile.migration
        networks:
            - database
        env_file:
            - .env.production.database.migration.local
        depends_on:
            database:
                condition: service_healthy

    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        stop_signal: SIGTERM
        stop_grace_period: 30s
        volumes:
            - server-logs:/app/Logs/
        networks:
            - server
        ports:
            - '8080:8080/tcp'
        env_file:
            - .env.production.server.local
        depends_on:
            database-migration:
                condition: service_completed_successfully
        restart: unless-stopped

volumes:
    database:
    server-logs:

networks:
    server:
    database:
